### ISSUE TITLE
PatientId issue

### ISSUE THREAD

**Issue by svelamur** [HL7-DaVinci/dtr#129]
Unable to invoke DTR app from Logica Sandbox. Still getting the following error:
"Failed to get a patientId from the app params or the authorization response."

**Comment by FrancisChristy** [comment]
same issue...did you get any fixes?


> Unable to invoke DTR app from Logica Sandbox. Still getting the following error:
> "Failed to get a patientId from the app params or the authorization response."

**Comment by svelamur** [comment]
Not yet. I tried again after your note. I am seeing following errors:
> Failure when fetching ValueSet ../../fhir/r4/ValueSet/$expand?url=http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1219.74 Make sure CRD has ValueSets Loaded.
> Failure when fetching ValueSet ../../fhir/r4/ValueSet/$expand?url=http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1219.78 Make sure CRD has ValueSets Loaded.
> Failure when fetching ValueSet ../../fhir/r4/ValueSet/$expand?url=http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1219.132 Make sure CRD has ValueSets Loaded.
> Failure when fetching ValueSet ../../fhir/r4/ValueSet/$expand?url=http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1219.106 Make sure CRD has ValueSets Loaded.
> Failure when fetching ValueSet ../../fhir/r4/ValueSet/$expand?url=http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.17.4077.3.2006 Make sure CRD has ValueSets Loaded.

It seems ValueSetCache.tar.gz needed to be added to Mitre's CRD app.

**Comment by KeeyanGhoreshi** [comment]
Are you launching directly from the logica sandbox?  I can't seem to replicate the error when launching out of the sandbox. The DTR app should finish launching even if it fails to load some of the value sets.

**Comment by svelamur** [comment]
Yes, I am trying to launch directly from Logica sandbox. Still unable to launch DTR.  See below the log trace:

Loading...

> fetching artifacts
> fetching questionnaire and elms
> ../../fhir/r4/Questionnaire/HomeOxygenTherapy
> fetched questionnaire successfully
> about to fetchElm (Library): ../../fhir/r4/Library?url=http://hl7.org/fhir/us/davinci-dtr/Library/HomeOxygenTherapy-prepopulation
> about to fetchElm (Library): ../../fhir/r4/Library?url=http://hl7.org/fhir/us/davinci-dtr/Library/BasicPatientInfo-prepopulation
> about to fetchElm (Library): ../../fhir/r4/Library?url=http://hl7.org/fhir/us/davinci-dtr/Library/BasicClinicalInfo-prepopulation
> about to fetchElm (Library): ../../fhir/r4/Library?url=http://hl7.org/fhir/us/davinci-dtr/Library/BasicPractitionerInfo-prepopulation
> fetched elms
> about to fetchElm (Library): ../../fhir/r4/Library/FHIRHelpers-4.0.0
> about to fetchElm (Library): ../../fhir/r4/Library/CDS_Connect_Commons_for_FHIRv400
> about to fetchElm (Library): ../../fhir/r4/Library/DTRHelpers
> about to fetchValueSet:
> about to fetchValueSet:
> about to fetchValueSet:
> about to fetchValueSet:
> about to fetchValueSet:
> about to fetchValueSet:
> about to fetchValueSet:
> about to fetchValueSet:
> about to fetchValueSet:
> about to fetchElmFile: ../../files/HomeOxygenTherapy/r4/HomeOxygenTherapyPrepopulation-0.1.0.cql
> fetched Elm
> about to fetchElm (Library): ../../fhir/r4/Library/FHIRHelpers-4.0.0
> about to fetchElmFile: ../../files/Shared/r4/BasicClinicalInfoPrepopulation-0.1.0.cql
> fetched Elm
> about to fetchElm (Library): ../../fhir/r4/Library/FHIRHelpers-4.0.0
> about to fetchElmFile: ../../files/Shared/r4/BasicPatientInfoPrepopulation-0.2.0.cql
> fetched Elm
> about to fetchElm (Library): ../../fhir/r4/Library/FHIRHelpers-4.0.0
> about to fetchElmFile: ../../files/Shared/r4/BasicPractitionerInfoPrepopulation-0.1.0.cql
> fetched Elm
> Failure when fetching ValueSet ../../fhir/r4/ValueSet/$expand?url=http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1219.25 Make sure CRD has ValueSets Loaded.
> Failure when fetching ValueSet ../../fhir/r4/ValueSet/$expand?url=http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1219.80 Make sure CRD has ValueSets Loaded.
> Failure when fetching ValueSet ../../fhir/r4/ValueSet/$expand?url=http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1219.79 Make sure CRD has ValueSets Loaded.
> about to fetchElmFile: ../../files/Shared/r4/FHIRHelpers-4.0.0.cql
> fetched Elm
> about to fetchElm (Library): ../../fhir/r4/Library/FHIRHelpers-4.0.0
> about to fetchElmFile: ../../files/Shared/r4/CDS_Connect_Commons_for_FHIRv400-1.0.2.cql
> fetched Elm
> Failure when fetching ValueSet ../../fhir/r4/ValueSet/$expand?url=http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1219.74 Make sure CRD has ValueSets Loaded.
> Failure when fetching ValueSet ../../fhir/r4/ValueSet/$expand?url=http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1219.77 Make sure CRD has ValueSets Loaded.
> about to fetchElm (Library): ../../fhir/r4/Library/FHIRHelpers-4.0.0
> about to fetchElmFile: ../../files/Shared/r4/DTRHelpers-0.1.0.cql
> fetched Elm
> Failure when fetching ValueSet ../../fhir/r4/ValueSet/$expand?url=http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1219.78 Make sure CRD has ValueSets Loaded.
> Failure when fetching ValueSet ../../fhir/r4/ValueSet/$expand?url=http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1219.106 Make sure CRD has ValueSets Loaded.
> Failure when fetching ValueSet ../../fhir/r4/ValueSet/$expand?url=http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.17.4077.3.2006 Make sure CRD has ValueSets Loaded.
> Failure when fetching ValueSet ../../fhir/r4/ValueSet/$expand?url=http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1219.132 Make sure CRD has ValueSets Loaded.
> about to fetchElmFile: ../../files/Shared/r4/FHIRHelpers-4.0.0.cql
> fetched Elm
> about to fetchElmFile: ../../files/Shared/r4/FHIRHelpers-4.0.0.cql
> fetched Elm
> about to fetchElmFile: ../../files/Shared/r4/FHIRHelpers-4.0.0.cql
> fetched Elm
> about to fetchElmFile: ../../files/Shared/r4/FHIRHelpers-4.0.0.cql
> fetched Elm
> about to fetchElmFile: ../../files/Shared/r4/FHIRHelpers-4.0.0.cql
> fetched Elm

**Comment by plarocque4** [comment]
I just reloaded the ValueSets cache so I'm thinking this will work again now. The problem is that our server is running in a docker container and certain cached data is lost every time it is restarted. The way to get it working again is to go to the rules page:
https://davinci-crd.logicahealth.org/data
and put in a VSAC API Key at the top and click "Reload Data". This will pull down the ValueSets to the server and have them ready to send out to the DTR app. Keeping the cache across restarts has been on our todo list for a little while. Hopefully we'll get this fixed soon.

**Comment by svelamur** [comment]
When I tried to test again, somehow I couldn't load Patients into Logica Sandbox when launched Mitre's DTR RI. Not sure whether there is a config issue with DTR (or) a problem with Sandbox.

**Comment by KeeyanGhoreshi** [comment]
If I'm not mistaken, loading patients occurs before the Sandbox involves the DTR app.  I'm assuming your workflow is, within the Sandbox UI, clicking on a DTR RI (local or not), choosing a persona/practitioner to login as, and then choosing a patient from the list.  If the patients aren't loading at that step, it's probably a problem with Sandbox.
