### ISSUE TITLE
Redirect the browser to the authorization server(keycloak 9.0.3) failed, getting invalid Parameter - redirect uri error

### ISSUE THREAD

**Issue by sivaselvask** [HL7-DaVinci/dtr#137]
I tried setting up the  **Documentation Requirements Lookup Service (DRLS)** System in my Windows machine

On selecting the patient and their corresponding Device/Medication/Service requests from the available list in **crd-request-generator** and on submitting the request, the **CRD server** responses back a set of Cards.
And on clicking the cards, smart on fhir(**DTR**) redirection happens and then failed in loading **keycloak** authentication page, because of invalid parameter in the redirect uri.

Following is the Redirected URL generated from DTR:

`http://localhost:8080/test-ehr/auth?response_type=code&client_id=app-login&scope=launch%20user%2FObservation.read%20user%2FPatient.read%20patient%2FObservation.read%20patient%2FPatient.read%20patient%2FCoverage.read%20patient%2FCondition.read%20user%2FPractitioner.read&redirect_uri=http%3A%2F%2Flocalhost%3A3005%2Findex&aud=http%3A%2F%2Flocalhost%3A8080%2Ftest-ehr%2Fr4&launch=338b46e3-b72f-4ca2-98f3-39e72dc6bc1e&state=36357282`

![crd-request-generator-ss](https://user-images.githubusercontent.com/65653985/117144347-73594d80-adcf-11eb-975f-608c7265c030.jpg)
![Keycloak-err](https://user-images.githubusercontent.com/65653985/117144367-781e0180-adcf-11eb-8117-2140ca56c9ff.jpg)

**Comment by cwanmtr** [comment]
First make sure the URL of your registered FHIR server ends with a "/" like this: http://localhost:8080/test-ehr/r4/
Let me know if you still get the same error.

**Comment by neoVipul** [comment]
I tried setting up Documentation Requirements Lookup Service locally all modules are up and running except redirection after keycloak authentication(i have given "*" redirect_uri in keycloak client app-login as its local environment) 

http://localhost:8180/auth/realms/ClientFhirServer/protocol/openid-connect/auth?response_type=code&client_id=app-login&scope=launch+user%2FObservation.read+user%2FPatient.read+patient%2FObservation.read+patient%2FPatient.read+patient%2FCoverage.read+patient%2FCondition.read+user%2FPractitioner.read&redirect_uri=http%3A%2F%2F0%3A0%3A0%3A0%3A0%3A0%3A0%3A1%3A8080%2Ftest-ehr%2F_auth%2F2f7352e0-21e7-4985-841a-a33d4e8dbed7%3Fredirect_uri%3Dhttp%3A%2F%2Flocalhost%3A3005%2Findex&aud=http%3A%2F%2Flocalhost%3A8080%2Ftest-ehr%2Fr4%2F&state=27185624&launch=2f7352e0-21e7-4985-841a-a33d4e8dbed7

Attached SS for reference.

![dtr-reg-git](https://user-images.githubusercontent.com/97103114/148341144-11e84e27-ccdc-4466-9977-d8e69f792886.PNG)
![crd-form-git](https://user-images.githubusercontent.com/97103114/148341154-4437c7ab-9ca2-4b0e-8d3d-f9b1b328a901.PNG)
![keycloak-git](https://user-images.githubusercontent.com/97103114/148341177-cb685919-9d91-4474-a015-7f6533d27a2f.PNG)
![error-git](https://user-images.githubusercontent.com/97103114/148341193-0e1cfa6e-de26-425e-8a13-9f9cae18bf9f.PNG)

**Comment by neoVipul** [comment]
Only for local deployment you can provide '*' in app-login client. 

![redirect-git](https://user-images.githubusercontent.com/97103114/148361954-00a98481-e08e-43e6-8ee9-236edd80ae81.PNG)
.

it worked for me

**Comment by RekhaChinta** [comment]
Facing the same issue in windows environment.

This is the redirect url that got generated

http://localhost:8180/realms/ClientFhirServer/protocol/openid-connect/auth?response_type=code&client_id=app-login&scope=launch+user%2FObservation.read+user%2FPatient.read+patient%2FObservation.read+patient%2FPatient.read+patient%2FCoverage.read+patient%2FCondition.read+user%2FPractitioner.read&redirect_uri=0%3A0%3A0%3A0%3A0%3A0%3A0%3A1%3A8080%2Ftest-ehr%2F_auth%2F18350934-4b65-4821-bbc7-cbd80b805072%3Fredirect_uri%3Dhttp%3A%2F%2Flocalhost%3A3005%2Findex&aud=http%3A%2F%2Flocalhost%3A8080%2Ftest-ehr%2Fr4&state=17126996&launch=18350934-4b65-4821-bbc7-cbd80b805072

Seems some issue with the redirect url 

edirect_uri=0%3A0%3A0%3A0%3A0%3A0%3A0%3A1%3A8080%2Ftest-ehr%2F_auth%2F18350934-4b65-4821-bbc7-

if i modify the protocol part and hit the url then i am able to see the login server. However i am seeing an empty screen after login

![image](https://user-images.githubusercontent.com/31544846/219361428-d447df05-5e06-4bac-af20-990f0e848595.png)

DTR url :

http://localhost:3005/index?state=193341&code=29e4818b-c1a8-4450-8617-7fdc41349dcb.4ce486bc-5dae-4228-9d6f-2c0089770f3b.5dd19d73-8f92-46a1-8751-c5aa3b5b5285


![image](https://user-images.githubusercontent.com/31544846/219362107-d1cc7265-17be-48a0-9e43-7d4d64babca9.png)

**Comment by KMCGit** [comment]
Facing this same issue still

**Comment by bstewartlg** [comment]
Unable to completely reproduce this issue, but a fix was checked in to the Test EHR server ( https://github.com/HL7-DaVinci/test-ehr/ ) that should at least partially resolve an issue with the redirect back from the Keycloak server to the Test EHR server.

Feel free to reopen if necessary.
