### ISSUE TITLE
Missing require bable plugin to run. 

### ISSUE THREAD

**Issue by rdingwell** [HL7-DaVinci/dtr#146]
I am receiving the following error when attempting to run the application.   Additional bable plugins are required to support the ? operator which seems to indicate and update to react-scripts is needed which includes the required plugin.   That or the offending line needs to be re-written in a more verbose but conventional syntax. 

ERROR in ./src/components/QuestionnaireForm/QuestionnaireForm.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/bobd/projects/drlsroot/dtr/src/components/QuestionnaireForm/QuestionnaireForm.jsx: Support for the experimental syntax 'optionalChaining' isn't currently enabled (728:16):

  726 |
  727 |     // change QuestionnaireResponse meta to show DTR QuestionnaireResponse instead of SDC QuestionnaireResponse
> 728 |     if (qr.meta?.profile.length){
      |                ^
  729 |       qr['meta']['profile'][0] = DTRQuestionnaireResponseURL;
  730 |     }
  731 |

**Comment by KeeyanGhoreshi** [comment]
this should be fixed
